kubectl delete -f es-client-deploy.yaml
kubectl delete -f es-config.yaml
kubectl delete -f es-curator.yaml
kubectl delete -f es-data-service.yaml
kubectl delete -f es-data-statefulset.yaml
kubectl delete -f es-discovery-service.yaml
kubectl delete -f es-ingress.yaml
kubectl delete -f es-master-deploy.yaml
kubectl delete -f es-service.yaml 
