apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zcp-system
resources:
- fluentd-aggregator-deployment.yaml
- fluentd-aggregator-svc.yaml
- fluentd-configmap.yaml
#configMapGenerator:
#- name: fluentd-config
#  files:
#  - config/fluentd-aggregator.conf
generatorOptions:
  disableNameSuffixHash: true