apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zcp-system
bases:
- ../../base
patchesJson6902:
- path: elasticsearch/es-data-statefulset_sc_patch.yaml
  target:
    group: apps
    kind: StatefulSet
    name: elasticsearch-data
    version: v1beta1