replicaCount: 1

image:
  repository: registry.au-syd.bluemix.net/cloudzcp/keycloak-proxy
  tag: 3.4.2.Final
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true 
  annotations: 
    ingress.bluemix.net/redirect-to-https: "True"
    #ingress.bluemix.net/ALB-ID: private-***-alb1 #private인 경우 수정 
  path: /
  hosts:
    - ***-logging.cloudzcp.io #CHANGE
  tls:
    - secretName: cloudzcp-io-cert
      hosts:
        - ***-logging.cloudzcp.io #CHANGE

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

affinity: 
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: beta.kubernetes.io/arch
          operator: In
          values:
          - amd64
        - key: role
          operator: In
          values:
          - logging

tolerations:
  - key: "logging"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

configmap:
  targetUrl: http://kibana:5602/
  realm: zcp
  realmPublicKey: ***                             #PublicKey of zcp realm
  authServerUrl: https://***-iam.cloudzcp.io/auth #CHANGE
  resource: logging
  secret: 69ca391e-4999-4779-96cc-6aef4875ea46    #check
  pattern: /*	
  rolesAllowed: log-manager
