apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: elasticsearch
    component: elasticsearch
    role: data
  name: elasticsearch-data
  namespace: zcp-system
spec:
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  serviceName: elasticsearch-data
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
      component: elasticsearch
      role: data
  template:
    metadata:
      labels:
        app: elasticsearch
        component: elasticsearch
        role: data
    spec:
      tolerations:
      - key: "logging"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
      restartPolicy: Always
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - "amd64"
              - key: role
                operator: In
                values:
                - "logging"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values:
                  - "elasticsearch"
              - key: "component"
                operator: In
                values:
                  - "elasticsearch"
              - key: "role"
                operator: In
                values:
                  - "data"
            topologyKey: "kubernetes.io/hostname"
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: "chmod"
        image: "registry.au-syd.bluemix.net/cloudzcp/elasticsearch:6.3.1"
        imagePullPolicy: "IfNotPresent"
        command: ["chmod", "777", "/data-dir"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /data-dir
      - name: "sysctl"
        image: "registry.au-syd.bluemix.net/cloudzcp/elasticsearch:6.3.1"
        imagePullPolicy: "IfNotPresent"
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-data
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
        image: "registry.au-syd.bluemix.net/cloudzcp/elasticsearch:6.3.1"
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "8192M"
        env:
        - name: "ES_JAVA_OPTS"
          value: "-Xms4096m -Xmx4096m"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: "elasticsearch-data"
          mountPath: "/usr/share/elasticsearch/data"
        - name: "elasticsearch-conf"
          mountPath: "/usr/share/elasticsearch/config/elasticsearch.yml"
          subPath: elasticsearch.yml
      volumes:
        - name: "elasticsearch-conf"
          configMap:
            name: es-configmap
            items:
              - key: data.yml
                path: elasticsearch.yml
      serviceAccountName: zcp-system-admin
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
      labels:
        app: elasticsearch
        component: elasticsearch
        role: data
      namespace: zcp-system
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: "200Gi"
      storageClassName: "ebs-gp2"
