kubectl create -f fluentd-aggregator-deployment.yaml
kubectl create -f fluentd-aggregator-svc.yaml
kubectl create -f fluentd-configmap.yaml
#kubectl create -f fluentd-ds.yaml
kubectl create -f fluentd-namespace.yaml
kubectl create -f fluentd-role-binding.yaml
kubectl create -f fluentd-role.yaml
kubectl create -f fluentd-service-account.yaml
kubectl create -f fluentd-svc.yaml
