kubectl delete -f fluentd-aggregator-deployment.yaml
kubectl delete -f fluentd-aggregator-svc.yaml
kubectl delete -f fluentd-configmap.yaml
#kubectl delete -f fluentd-ds.yaml
kubectl delete -f fluentd-namespace.yaml
kubectl delete -f fluentd-role-binding.yaml
kubectl delete -f fluentd-role.yaml
kubectl delete -f fluentd-service-account.yaml
kubectl delete -f fluentd-svc.yaml
