apiVersion: v1
kind: Service
metadata:
  labels:
    app: kibana
    component: kibana
  name: kibana
  namespace: zcp-system
spec:
  selector:
    app: kibana
    component: kibana
  ports:
  - port: 5602
    protocol: TCP
    targetPort: 5602
  type: ClusterIP
